# Update system timezone if needed
#
- name: Check current timezone
  shell: timedatectl | awk '/Time zone:/ {print $3}'
  register: ntp_current_timezone
  changed_when: false
  tags: [ntp]

- name: Change timezone
  command: "timedatectl set-timezone {{ ntp_timezone }}"
  when: "ntp_current_timezone.stdout != ntp_timezone"
  tags: [ntp]
