# Version of git that should be installed
git_version: "2.30.1"

# Location where Git should be installed
git_install_path: /usr/local/git

# Location of files for git sources
git_sources_location: /usr/src

# User that will build Git from sources
git_build_user: developer

# Group of the build user.
git_build_group: developer
