# Manage SSH
- import_tasks: ssh.yml
  when: "centos_manage_ssh == true"



# Disable Transparent Huge Pages
- import_tasks: thp.yml
  when: "centos_disable_thp == true"



# Manage logrotate scripts
- import_tasks: logrotate.yml
  when: "centos_manage_logrotate == true"



# Manage iptables
- import_tasks: iptables.yml
  when: "centos_manage_iptables == true"
