# Version of OpenSSL that should be installed
openssl_version: "1.1.1i"

# Path where OpenSSL will be installed. NO trailing slash at the end!
openssl_install_path: /usr/local/openssl

# Location of files for OpenSSL sources
openssl_sources_location: /usr/src

# User that will build OpenSSL
openssl_build_user: developer

# Group of the build user
openssl_build_group: developer
