# List of users to give access to CLI:
awscli_users:
  - developer

# Should credential files and defaults be also set up for root account?
awscli_users_root: yes

# AWS Access Key ID
awscli_aws_access_key_id: AKIAI44QH8DHBEXAMPLE

# AWS Secret Access Key
awscli_aws_secret_access_key: e7MtGbClwBF/2Zp9Utk/h3yCo8nvbEXAMPLEKEY

# Default region name
awscli_default_region_name: us-east-1

# Default output format
awscli_default_output_format: text
