# List of groups to remove from the system
users_groups_to_remove: []

# List of groups that should be present
users_groups_to_create:
  - wheel
  - www

# List of users to remove from the system
users_to_remove: []

# List of users to create
users_to_create:
  - name: developer
    password: "$6$s60kc6yAy4$qqFLRihYSdVP9EVPV6bP7X3nPtItMiqPDmyMAhsMybWsWRmHvOVYHEwNU/okPsemJ0Aa3RfCrINHoNsbpNAQL1"
    authorized_keys: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
    generate_ssh_key: yes
    groups:
      - www
      - wheel
